controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    manipulator_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

manipulator_controller:
  ros__parameters:
    joints:
      - mani_base
      - elbow_forearm
      - palm_left_finger
    interface_name: position
